kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "sample-build" 
spec:
  source: 
    type: "Binary"
  strategy: 
    type: "Docker"
    dockerStrategy:
      dockerfilePath: "."
  output: 
    to:
      kind: "ImageStream"
      name: "sample"